version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PYTHONPATH: "$PYTHONPATH:/opt/placenerd/app"
      ENV: "DEVELOPMENT"
      NLTK_DATA: "/opt/placenerd/nltk_data"
      DOWNLOAD_DATASET: "book"
    working_dir: /opt/placenerd/app
    command: /bin/bash -c "python entrypoint.py"
    volumes: 
        - ./:/opt/placenerd
