version: '2'
services:
    placenerd:
        build: .
        command: tail -f analysis.log
        working_dir: /opt/placenerd/analysis
        environment:
            - NLTK_DATA=/opt/placenerd/analysis/nltk_data
            - DOWNLOAD_DATASET=book
            - PYTHONPATH=$PYTHONPATH:/opt/placenerd/analysis
        volumes:
            - ./:/opt/placenerd/analysis
        ports:
            - "8888:8888"
        
